<?php
require_once 'admin_header.php';
?>

<div class="main-content">
    <div class="page-header">
        <h2>System Reports</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="admin_dashboard.php" class="breadcrumb-item"><i class="anticon anticon-home"></i> Dashboard</a>
                <span class="breadcrumb-item active">System Reports</span>
            </nav>
        </div>
    </div>
    
    <!-- Report Filter -->
    <div class="card">
        <div class="card-body">
            <h5>Generate Report</h5>
            <form id="reportFilterForm" class="mt-3">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Report Type</label>
                            <select class="form-control" name="report_type" id="reportType">
                                <option value="users">User Report</option>
                                <option value="transactions">Transaction Report</option>
                                <option value="cases">Case Report</option>
                                <option value="financial">Financial Summary</option>
                                <option value="activity">Activity Log</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Start Date</label>
                            <input type="date" class="form-control" name="start_date" id="startDate">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>End Date</label>
                            <input type="date" class="form-control" name="end_date" id="endDate">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>&nbsp;</label>
                            <button type="button" class="btn btn-primary btn-block" id="generateReport">
                                <i class="anticon anticon-file-pdf"></i> Generate Report
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
    <!-- Quick Reports -->
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body text-center">
                    <i class="anticon anticon-team font-size-40 text-primary"></i>
                    <h5 class="mt-3">User Activity Report</h5>
                    <p class="text-muted">Generate comprehensive user activity and engagement report</p>
                    <button class="btn btn-primary btn-sm" onclick="generateQuickReport('users')">
                        <i class="anticon anticon-download"></i> Download
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body text-center">
                    <i class="anticon anticon-dollar font-size-40 text-success"></i>
                    <h5 class="mt-3">Financial Report</h5>
                    <p class="text-muted">View all transactions, deposits, and withdrawals</p>
                    <button class="btn btn-success btn-sm" onclick="generateQuickReport('financial')">
                        <i class="anticon anticon-download"></i> Download
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body text-center">
                    <i class="anticon anticon-file-protect font-size-40 text-warning"></i>
                    <h5 class="mt-3">Case Management Report</h5>
                    <p class="text-muted">Summary of all cases and their current status</p>
                    <button class="btn btn-warning btn-sm" onclick="generateQuickReport('cases')">
                        <i class="anticon anticon-download"></i> Download
                    </button>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Report History -->
    <div class="card">
        <div class="card-body">
            <h5 class="mb-3">Recent Reports</h5>
            <div class="table-responsive">
                <table class="table table-hover" id="reportsTable">
                    <thead>
                        <tr>
                            <th>Report Type</th>
                            <th>Date Range</th>
                            <th>Generated By</th>
                            <th>Generated On</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><span class="badge badge-primary">User Report</span></td>
                            <td>2024-01-01 to 2024-01-31</td>
                            <td>Admin User</td>
                            <td><?= date('Y-m-d H:i') ?></td>
                            <td>
                                <button class="btn btn-sm btn-primary">
                                    <i class="anticon anticon-download"></i>
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<?php require_once 'admin_footer.php'; ?>

<script>
$(document).ready(function() {
    // Set default dates
    const today = new Date();
    const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, today.getDate());
    $('#endDate').val(today.toISOString().split('T')[0]);
    $('#startDate').val(lastMonth.toISOString().split('T')[0]);
    
    $('#generateReport').click(function() {
        const reportType = $('#reportType').val();
        const startDate = $('#startDate').val();
        const endDate = $('#endDate').val();
        
        if (!startDate || !endDate) {
            toastr.error('Please select start and end dates');
            return;
        }
        
        toastr.info('Generating report...');
        
        // TODO: Replace with actual API endpoint when backend is ready
        // $.ajax({
        //     url: 'admin_ajax/generate_report.php',
        //     type: 'POST',
        //     data: { type: reportType, start_date: startDate, end_date: endDate },
        //     success: function(response) {
        //         if (response.success) {
        //             toastr.success('Report generated successfully');
        //             window.location.href = response.download_url;
        //         }
        //     }
        // });
        setTimeout(() => {
            toastr.success('Report generated successfully (demo mode)');
        }, 1000);
    });
});

function generateQuickReport(type) {
    toastr.info('Generating ' + type + ' report...');
    
    // TODO: Replace with actual API endpoint when backend is ready
    // $.ajax({
    //     url: 'admin_ajax/generate_quick_report.php',
    //     type: 'POST',
    //     data: { type: type },
    //     success: function(response) {
    //         if (response.success) {
    //             window.location.href = response.download_url;
    //         }
    //     }
    // });
    setTimeout(() => {
        toastr.success('Report generated successfully (demo mode)');
    }, 1000);
}
</script>


